### ISSUE TITLE
Support for other platforms than Android

### ISSUE THREAD

**Issue by hsteinmaurer** [PureWeen/ShanedlerSamples#1]
First of all: the solution is a nice approach to get control over the soft keyboard in Android. Thanks for that, I am using it in a project that I am working on.
Rright now the solution only works for Android, but fails to build for other platforms. I fixed it with directives, so that the extended keyboard functionalities are relevant for Android only.
Do you have any idea/plans to extend compatibilty to other platforms?

**Comment by PureWeen** [comment]
@hsteinmaurer the version that's up now should work for iOS

**Comment by hsteinmaurer** [comment]
Thanks a lot for considering my input in the update!
