### ISSUE TITLE
[Keyboard] Auto-scroll does not work on WebViews

### ISSUE THREAD

**Issue by vhugogarcia** [PureWeen/ShanedlerSamples#10]
Hello @PureWeen ,

Thanks for adding the keyboard fix to the package. However, I noticed a minor missing feature, when we have a **Webview** in a screen and that Webview has a form with several fields, if I tap a field of that form within the Webview the keyboard is still covering the form field. Since the web page does not allow to zoom or scroll, there is no way for us to scroll manually. 

This happens on iOS, iPadOS and also on Android. 

Thank you!

**Comment by PureWeen** [comment]
@tj-devel709 

FYI: This work is also part of our current .NET8 previews so you can test there without using this code

**Comment by vhugogarcia** [comment]
This is not an issue anymore, thanks to .NET MAUI 8. 

I am closing this issue. 😎
