### ISSUE TITLE
TabbedPageWorkarounds: blank page after adding a tab

### ISSUE THREAD

**Issue by tranb3r** [PureWeen/ShanedlerSamples#4]
I've reported a few days ago [here ](https://github.com/dotnet/maui/issues/9743#issuecomment-1453699211) that I experienced an exception when programmatically adding a tab to a TabbedPage.

The exception has been fixed in version 1.2.4 of the TabbedPageWorkarounds.
However, when adding a tab, the current tab now becomes blank.

Could you please take a look? Do you need a repro?
Thanks!

**Comment by PureWeen** [comment]
@tranb3r yea can you add a repro? 

Hopefully I can make this one work :-/ 

I did a PR over on MAUI that once we back port will make this all easier but, in the mean time 🤞

**Comment by tranb3r** [comment]
I've updated my repro here: https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageBlank

Just launch the app and click on 'add tab' button. It's supposed to add a new tab to the tabbedpage.
- with 1.2.3: there was an exception
- with 1.2.4: the exception has been fixed, but the current tab becomes blank

**Comment by PureWeen** [comment]
@tranb3r alright pushed up another hack on the stack :-) 

It'll flicker a little bit but I don't think I can fix that currently. I have some updates percolating inside MAUI that we'll hopefully backport to NET7 and then I can just remove all these hacks and the original code should work fine.

**Comment by tranb3r** [comment]
I've tested 1.2.6. 
'add tab' does work. However, navigation is broken.
To reproduce, open the same sample, click on 'add tab' and then 'push page'.

Could you please take a look?
Thanks!

**Comment by PureWeen** [comment]
yea this is a tricky one :-/ I'll see if I can find a workaround, worst case we have a PR that will make it out to an upcoming 7.0 SR that should fix the cast exception

**Comment by tranb3r** [comment]
I've just tested the new maui SR (7.0.81).
The blank page issue is still here.
Could you please help and provide a fix?

**Comment by PureWeen** [comment]
> I've just tested the new maui SR (7.0.81). The blank page issue is still here. Could you please help and provide a fix?

Try the latest pushed version

I still had the workaround in place that didn't really work.

**Comment by tranb3r** [comment]
I've tried all versions of your nuget.
The TabbedPage is always broken.
Either it crashes, or I get a blank page, or the navigation does not work.

**Comment by tranb3r** [comment]
Version 1.3.1 has just appeared in my nuget feed.
I've tested it and it seems all issues are now gone.
Thanks a lot!

**Comment by espritm** [comment]
Thanks you for providing this workaround !
