### ISSUE TITLE
Add net7.0 TFM

### ISSUE THREAD

**Issue by tranb3r** [PureWeen/ShanedlerSamples#6]
My MAUI app has all UI things in an assembly that is pure net7.0 (no platform specific code).
So when I want to add a packagereference to this assembly, it needs to support net7.0 TFM (even if it's code for android or ios).

Most MAUI plugins do support net6.0 or net7.0 TFM, but not this one. 
Could you please add it?

As a workaround, I can still add the packagereference to the top-level assembly in my app, which of course supports net7.0-android and net7.0-ios TFMs. But I'd rather be able to get rid of this constraint.

Thanks!

**Comment by PureWeen** [comment]
👍

**Comment by tranb3r** [comment]
Thanks!
