### ISSUE TITLE
Modal page with editor as an entry page is cut

### ISSUE THREAD

**Issue by gabsamples6** [PureWeen/ShanedlerSamples#7]
Hi this is a duplicate up to a point of 

https://github.com/dotnet/maui/issues/10978
https://github.com/dotnet/maui/pull/11356
https://github.com/dotnet/maui/issues/11274

1. Using shell (android)
2. Navigate to a modal page 
3. have an Editor on the modal page  type some rubbish and keep going - as soon as the text reaches a certain length , you will see the page behaving erratically and cut.. 

It works with an entry as you dont type lots of text..

**What breaks it is if you set AutoSize=TextChanges and keep typing**

I will create a repo if not clear

**Comment by gabsamples6** [comment]
Removed a superflous grid and no longer happening..

**Comment by PureWeen** [comment]
@gabsamples6 can you paste the xaml of your modal that was causing the issue? I'm curious still to see a repro.
